// AUTH
// login ADMIN
POST http://localhost:3333/auth/login
content-type: application/json

{
  "email": "gloriamaria@globo.com",
  "password": "Ga39712Glo@"
}
###

// login usuario - permissão de visualizar somente
POST http://localhost:3333/auth/login
content-type: application/json

{
  "email": "jobn2@zmail.com",
  "password": "Abc1234@",
  "token": "JCK4YE"
}
###


// USERS
// registro de novo usuário
POST http://localhost:3333/users/register
content-type: application/json

{ 
  "name": "Glória Maria da Globo",
  "email": "gloriamaria@globo.com",
  "password": "Ga39712Glo@",
  "phone": "+55 65 99999-0000",
  "profileUrl" : "https://profile.com/127",
  "recoveryToken": "no-token",
  "tokenExpiration": null,
  "twoFactorAuth": false,
  "workingHours": "Segunda à sexta das 8:00-12:00 e 13:30-17:30"
}
###


POST http://localhost:3333/users/esqueci-senha
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW5pc3RyYWRvciIsImVtYWlsIjoiYWRtaW5Aem1haWwuY29tLmJyIiwiaWF0IjoxNzM3NzE3MTMyLCJleHAiOjE3Mzc3MjA3MzJ9.5W-4Na7-W9Nfab3U_zH4Rpx8tJgJakTnS7Fs6umxHKA

{
  "user": {
    "email": "joao@zmail.com"
  }
}
###

PUT http://localhost:3333/users/recuperar-senha/?email=joao@zmail.com&token=a5GizH
content-type: application/json
Authorization: Bearer 123456

{
  "newPassword": "novaSenhaTeste"
}
###

GET http://localhost:3333/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW5pc3RyYWRvciIsImVtYWlsIjoiYWRtaW5Aem1haWwuY29tLmJyIiwiaWF0IjoxNzM3NzE3MTMyLCJleHAiOjE3Mzc3MjA3MzJ9.5W-4Na7-W9Nfab3U_zH4Rpx8tJgJakTnS7Fs6umxHKA
###

// busca usuário por id
GET http://localhost:3333/users/d0ac7682-3757-4881-beed-50687fbc0f12
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW5pc3RyYWRvciIsImVtYWlsIjoiYWRtaW5Aem1haWwuY29tLmJyIiwiaWF0IjoxNzM3NzE3MTMyLCJleHAiOjE3Mzc3MjA3MzJ9.5W-4Na7-W9Nfab3U_zH4Rpx8tJgJakTnS7Fs6umxHKA
###


// ativa / desativa usuário
POST http://localhost:3333/users/toggle/d0ac7682-3757-4881-beed-50687fbc0f12
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW5pc3RyYWRvciIsImVtYWlsIjoiYWRtaW5Aem1haWwuY29tLmJyIiwiaWF0IjoxNzM3NzE3MTMyLCJleHAiOjE3Mzc3MjA3MzJ9.5W-4Na7-W9Nfab3U_zH4Rpx8tJgJakTnS7Fs6umxHKA
###


// atualiza dados do usuário
PUT http://localhost:3333/users
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW5pc3RyYWRvciIsImVtYWlsIjoiYWRtaW5Aem1haWwuY29tLmJyIiwiaWF0IjoxNzM3NzE3MTMyLCJleHAiOjE3Mzc3MjA3MzJ9.5W-4Na7-W9Nfab3U_zH4Rpx8tJgJakTnS7Fs6umxHKA

{
  "id": "d1855e9e-e489-43b1-9ae6-0168d83cfa82",
  "name": "Joao J. J.",
  "email": "johnjj@zmail.com",
  "password": "123456Jj@",
  "phone": "+55 00 99999-1111",
  "profileUrl" : "https://profile.com/123",
  "recoveryToken": "no-token",
  "tokenExpiration": null,
  "twoFactorAuth": true,
  "workingHours": "Segunda à sexta das 8:00-12:00 e 13:30-17:30"
}
###

// exclui usuário 
// - somente para testes, após finalizado projeto deve ser removido
DELETE http://localhost:3333/users/13a9b446-f4c0-43a4-9e33-f27b41b033f5
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW5pc3RyYWRvciIsImVtYWlsIjoiYWRtaW5Aem1haWwuY29tLmJyIiwiaWF0IjoxNzM3NzE3MTMyLCJleHAiOjE3Mzc3MjA3MzJ9.5W-4Na7-W9Nfab3U_zH4Rpx8tJgJakTnS7Fs6umxHKA
###


// Ola Mundo
GET http://localhost:3333
###

