// AUTH
// login - get token
POST http://localhost:3333/auth/login
content-type: application/json

{
  "email": "admin@zmail.com.br",
  "password": "123456Aa@"
}
###


POST http://localhost:3333/profile
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW5pc3RyYWRvciIsImVtYWlsIjoiYWRtaW5Aem1haWwuY29tLmJyIiwiaWF0IjoxNzM3NzE3MTMyLCJleHAiOjE3Mzc3MjA3MzJ9.5W-4Na7-W9Nfab3U_zH4Rpx8tJgJakTnS7Fs6umxHKA

{ 
  "name": "ADMIN_TESTE",
  "description": "Perfil Teste"
}
###


GET http://localhost:3333/profile
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW5pc3RyYWRvciIsImVtYWlsIjoiYWRtaW5Aem1haWwuY29tLmJyIiwiaWF0IjoxNzM3NzE3MTMyLCJleHAiOjE3Mzc3MjA3MzJ9.5W-4Na7-W9Nfab3U_zH4Rpx8tJgJakTnS7Fs6umxHKA
###


GET http://localhost:3333/profile/2
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW5pc3RyYWRvciIsImVtYWlsIjoiYWRtaW5Aem1haWwuY29tLmJyIiwiaWF0IjoxNzM3NzE3MTMyLCJleHAiOjE3Mzc3MjA3MzJ9.5W-4Na7-W9Nfab3U_zH4Rpx8tJgJakTnS7Fs6umxHKA
###


PUT http://localhost:3333/profile 
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW5pc3RyYWRvciIsImVtYWlsIjoiYWRtaW5Aem1haWwuY29tLmJyIiwiaWF0IjoxNzM3NzE3MTMyLCJleHAiOjE3Mzc3MjA3MzJ9.5W-4Na7-W9Nfab3U_zH4Rpx8tJgJakTnS7Fs6umxHKA

{ 
  "id": 4,
  "name": "ADMIN_TESTE2",
  "description": "Perfil Teste"
}
###


// ativa / desativa usuário
POST http://localhost:3333/profile/toggle/3
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW5pc3RyYWRvciIsImVtYWlsIjoiYWRtaW5Aem1haWwuY29tLmJyIiwiaWF0IjoxNzM3NzE3MTMyLCJleHAiOjE3Mzc3MjA3MzJ9.5W-4Na7-W9Nfab3U_zH4Rpx8tJgJakTnS7Fs6umxHKA
###


// - somente para testes, após finalizado projeto deve ser removido
DELETE http://localhost:3333/profile/3
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQWRtaW5pc3RyYWRvciIsImVtYWlsIjoiYWRtaW5Aem1haWwuY29tLmJyIiwiaWF0IjoxNzM3NzE3MTMyLCJleHAiOjE3Mzc3MjA3MzJ9.5W-4Na7-W9Nfab3U_zH4Rpx8tJgJakTnS7Fs6umxHKA
###

